
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 14 14:29:24 CET 2021
//----------------------------------------------------

package mjcompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 16;
  public static final int ASSGN_DIV = 30;
  public static final int CONST = 10;
  public static final int EQUALS = 35;
  public static final int GRTEQ = 38;
  public static final int GRT = 37;
  public static final int SEMICOLN = 12;
  public static final int LPAREN = 8;
  public static final int DECR = 21;
  public static final int NUM_CONST = 14;
  public static final int ASSGN_MUL = 32;
  public static final int ASSGN_ADD = 28;
  public static final int LESS = 39;
  public static final int ASSGN_MOD = 31;
  public static final int RPAREN = 9;
  public static final int NEQUALS = 36;
  public static final int COMMA = 13;
  public static final int INC = 20;
  public static final int DIV = 26;
  public static final int LESSEQ = 40;
  public static final int EOF = 0;
  public static final int EQUAL = 11;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 25;
  public static final int ADD = 24;
  public static final int MOD = 27;
  public static final int IDENT = 3;
  public static final int VOID = 17;
  public static final int ASSGN_SUB = 29;
  public static final int COLON = 34;
  public static final int LBRACE = 4;
  public static final int QUESTMARK = 33;
  public static final int LSQUARE = 6;
  public static final int READ = 18;
  public static final int RSQUARE = 7;
  public static final int RBRACE = 5;
  public static final int BOOL_CONST = 15;
  public static final int SUB = 22;
  public static final int PRINT = 19;
}

